In [1]:
import tushare as ts
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import plotly
import plotly.plotly as py
import plotly.graph_objs as go
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
from datetime import datetime

In [ ]:
# ts.get_hist_data('600030') # 600030 中信证券
# ts.get_today_all() # 一次性获取当前交易所有股票的行情数据

In [32]:
df = ts.get_index() # 获取大盘指数实时行情列表
df = pd.DataFrame(df)
select = ['上证指数', '深证综指', '沪深300', '创业板指']
df = df.loc[df['name'].isin(select)]
df

,code,name,change,open,preclose,close,high,low,volume,amount
0,000001,上证指数,-0.06,3088.0076,3091.1909,3089.4286,3092.6634,3083.9506,26011639,383.3183
10,000300,沪深300,0.15,3811.2852,3807.5781,3813.1411,3816.9737,3805.7683,16227157,289.0449
17,399006,创业板指,1.28,1702.3660,1702.9300,1724.7880,1724.9640,1702.3660,323899692,50.4476
21,399106,深证综指,0.67,1748.6630,1747.9560,1759.7040,1759.7850,1748.6630,3388194244,471.5660

In [41]:
pingan = ts.get_realtime_quotes('601318')[['code', 'name', 'pre_close', 'price', 'high', 'low', 'bid', 'ask', 'volume', 'amount', 'time', 'date']]
# pingan = pingan[['code', 'name', 'pre_close', 'price', 'high', 'low', 'bid', 'ask', 'volume', 'amount', 'time', 'date']]
moutai = ts.get_realtime_quotes('600519')[['code', 'name', 'pre_close', 'price', 'high', 'low', 'bid', 'ask', 'volume', 'amount', 'time', 'date']]
cmb = ts.get_realtime_quotes('600036')[['code', 'name', 'pre_close', 'price', 'high', 'low', 'bid', 'ask', 'volume', 'amount', 'time', 'date']]
cib = ts.get_realtime_quotes('601166')[['code', 'name', 'pre_close', 'price', 'high', 'low', 'bid', 'ask', 'volume', 'amount', 'time', 'date']]
midea = ts.get_realtime_quotes('000333')[['code', 'name', 'pre_close', 'price', 'high', 'low', 'bid', 'ask', 'volume', 'amount', 'time', 'date']]
gree = ts.get_realtime_quotes('000651')[['code', 'name', 'pre_close', 'price', 'high', 'low', 'bid', 'ask', 'volume', 'amount', 'time', 'date']]
# A50 = pingan.append(moutai)
A50 = pd.concat([pingan, moutai, cmb, cib, midea, gree], axis = 0)
A50

,code,name,pre_close,price,high,low,bid,ask,volume,amount,time,date
0,601318,中国平安,63.530,63.650,63.850,63.210,63.640,63.650,17658055,1122276726.000,10:06:57,2018-06-05
0,600519,贵州茅台,781.970,786.380,790.000,777.230,786.000,786.380,1631610,1277875911.000,10:06:57,2018-06-05
0,600036,招商银行,29.250,29.120,29.320,29.030,29.110,29.120,7125551,207661354.000,10:06:57,2018-06-05
0,601166,兴业银行,16.010,15.970,16.020,15.950,15.970,15.980,5825648,93090046.000,10:06:57,2018-06-05
0,000333,美的集团,53.990,54.250,54.820,53.720,54.240,54.250,10086651,547613608.920,10:06:57,2018-06-05
0,000651,格力电器,47.810,48.030,48.380,47.930,48.030,48.040,29014199,1396419236.130,10:06:57,2018-06-05

In [3]:
# 上证指数
#ts.get_realtime_quotes('sh')
# 上证指数，深圳成指，沪深300指数，上证50，中小板，创业板
# ts.get_realtime_quotes(['sh', 'sz', 'hs300', 'sz50', 'zxb', 'cyb'])
# 或者混搭
# ts.get_realtime_quotes(['sh','600848'])

# sh = ts.get_h_data('000001', index = True) # 000001 = sh
# sz = ts.get_h_data('399106', index = True) # 399106 = 深圳综合指数
# cyb = sz = ts.get_h_data('399006', index = True) # 399006 = cyb

# sh.close.head(60).plot(linewidth = 3, figsize =(15, 7))
# sz.close.plot(figsize =(15, 7))
# cyb.close.plot(figsize =(15, 7))
# plot(sh.close, sz.close)


#plot([go.Scatter(x = sh.index, y = sh.close)])